name: lru
description: LRU (Least recently used) cache with additional weak map layer. 
version: 1.0.0
homepage: https://github.com/Zekfad/lru_cache
repository: https://github.com/Zekfad/lru_cache
issue_tracker: https://github.com/Zekfad/lru_cache/issues
# documentation: https://pub.dev/documentation/lru/latest/
topics:
  - cache
  - lru

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.12.0
  weak_cache: ^2.1.3

dev_dependencies:
  test: ^1.25.14
  zekfad_lints: ^2.2.0
