name: lru
description: Cache based on least recently used eviction strategy
  with additional typed data support and weak cache layer. 
version: 1.0.3
homepage: https://github.com/Zekfad/lru_cache
repository: https://github.com/Zekfad/lru_cache
issue_tracker: https://github.com/Zekfad/lru_cache/issues
# documentation: https://pub.dev/documentation/lru/latest/
topics:
  - cache
  - lru
  - data-structures

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.12.0
  weak_cache: ^2.1.3

dev_dependencies:
  test: ^1.25.14
  zekfad_lints: ^2.3.0
